### ISSUE TITLE
[제안] [STYLE] UIColor Extension

### ISSUE THREAD

**Issue by tngusmiso** [Nexters/momo-iOS#12]
## 제안
`UIColor(displayP3Red: CGFloat, green: CGFloat, blue: CGFloat, alpha: CGFloat)` 
이걸 사용하려면 각 값을 0~1 사이로 입력해야하므로
Figma에 있는 rgba 값을 사용하려면 255로 나눠주어야 하는 불편함이 있습니다.
Figma 컬러값을 그대로 사용할 수 있도록 extension 코드를 추가하면 어떨까요?
``` Swift
UIColor(displayP3Red: 128/255, green: 135/255, blue: 201/255, alpha: 1)
```
<img width="239" alt="image" src="https://user-images.githubusercontent.com/37800715/215557894-f5810973-2210-4980-8952-779ddfa58681.png">

```Swift
extensnion UIColor {
    /// Figma rgba를 그대로 활용할 수 있는 확장 메소드.
    /// rgb는 0~255 기준으로, alpha는 0~1 기준으로 사용하면 된다.
    static func rgba(_ red: CGFloat, _ green: CGFloat, _ blue: CGFloat, _ alpha: CGFloat) {
        return UIColor(displayP3Red: red/255, green: green/255, blue: blue/255, alpha: alpha)
    }
}
```

```Swift
view.backgroundColor = .rgba(128, 135, 201, 1)
```

**Comment by dayo2n** [comment]
좋아요! 저도 저렇게 써와서 따로 코드를 추가해도 되는지 고민하고 있었는데 좋은 제안인 것 같습니다 🙊🙊

**Comment by josushell** [comment]
넘 좋습니다! 저도 extension 만들어서 쓰고 있었어용
