### ISSUE TITLE
[제안] [STYLE] UIView Extension

### ISSUE THREAD

**Issue by josushell** [Nexters/momo-iOS#13]
addSubview() 할때 여러개의 subview를 하나씩 add 하는게 불편해서 다음과 같은 extension을 작성해서 쓰고 있는데 이 프로젝트에도 적용해보면 어떨까요?

<img width="781" alt="스크린샷 2023-01-31 오후 1 58 49" src="https://user-images.githubusercontent.com/63590121/215669759-67c2fe58-6a5d-43ff-944e-c404a3807df8.png">

예를 들면 이렇게 쓸 수 있어요!

<img width="802" alt="스크린샷 2023-01-31 오후 2 03 05" src="https://user-images.githubusercontent.com/63590121/215670152-71922457-79a4-4ce8-a2e6-b25d741f3c5a.png">

**Comment by dayo2n** [comment]
오 완전 좋아요 안그래도 린트가 body가 너무 길다고 했는데 이거면 해결될 것 같군요 🤓

**Comment by tngusmiso** [comment]
좋습니당!
