### ISSUE TITLE
[제안][STYLE] UIStackView Extension

### ISSUE THREAD

**Issue by dayo2n** [Nexters/momo-iOS#23]
@josushell @tngusmiso #13 제안의 UIView extension과 같은 방식으로
UIStackView의 addArrangedSubview()를 한 줄로 처리할 수 있도록 프로젝트에 적용해도 될까요??

<img width="306" alt="스크린샷 2023-02-03 오후 5 16 13" src="https://user-images.githubusercontent.com/57654681/216548521-7ca53532-607f-4668-9588-c4917266a545.png">

사용 방식은 아래와 같습니다 😽
<img width="923" alt="스크린샷 2023-02-03 오후 5 17 58" src="https://user-images.githubusercontent.com/57654681/216548535-aa311443-2dfe-451f-a2a7-c85e809283ee.png">
여러 줄로 쓰고 보니 린트 warning이 떠서 제안드립니당

**Comment by tngusmiso** [comment]
대박 좋아여~~~~~~
근데 Lint 20줄 좀 짧은 것 같아서 늘리면 어떨까요..? 한.. 30~40줄..?

**Comment by josushell** [comment]
넘 좋습니다!!
린트 늘리는거 대찬성이에요 😉

**Comment by dayo2n** [comment]
그건 더 좋아요!! 🥹🥹🥹🥹

**Comment by tngusmiso** [comment]
다연님 extension 추가하는 김에 lint 수정도 부탁드려도 될까욤ㅎㅎ🫶

**Comment by dayo2n** [comment]
오키요 곧 수정해서 올리께요 😎😚
